import type { TemplateCommandSet, TemplateScaffoldOptions } from "./types.js";

export function renderJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

export function renderManifestSchemaJson(): string {
  return renderJson({
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://piphi.io/schemas/piphi-manifest.schema.json",
    title: "PiPhi Runtime Manifest",
    type: "object",
    required: ["manifest_version", "id", "name", "version", "runtime", "api", "capabilities"],
    properties: {
      $schema: { type: "string" },
      manifest_version: { type: "string" },
      id: { type: "string", minLength: 1 },
      name: { type: "string", minLength: 1 },
      version: { type: "string", minLength: 1 },
      description: { type: "string" },
      license: { type: "string" },
      metadata: { type: "object" },
      maintainer: {
        type: "object",
        properties: {
          name: { type: "string" },
          website: { type: "string" },
        },
      },
      runtime: {
        type: "object",
        required: ["linux"],
        properties: {
          linux: {
            type: "object",
            required: ["container"],
            properties: {
              container: {
                type: "object",
                required: ["image", "ports"],
                properties: {
                  image: { type: "string" },
                  ports: {
                    type: "array",
                    minItems: 1,
                    items: {
                      type: "object",
                      required: ["container"],
                      properties: {
                        container: { type: "integer", minimum: 1, maximum: 65535 },
                        host: { type: "integer", minimum: 1, maximum: 65535 },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      api: {
        type: "object",
        required: ["required", "endpoints"],
        properties: {
          required: {
            type: "array",
            items: { type: "string" },
          },
          endpoints: {
            type: "object",
            additionalProperties: { type: "string", pattern: "^/" },
          },
        },
      },
      capabilities: { type: "object" },
      commands: { type: "object" },
      entities: { type: "array" },
    },
  });
}

export function renderCurlExample(options: TemplateScaffoldOptions): string {
  return `#!/usr/bin/env bash
set -euo pipefail

BASE_URL="\${BASE_URL:-http://127.0.0.1:${options.port}}"

curl -sS "$BASE_URL/health"
curl -sS "$BASE_URL/diagnostics"
curl -sS "$BASE_URL/ui-config"
curl -sS -X POST "$BASE_URL/discover" -H 'content-type: application/json' -d '{"inputs":{"host":"127.0.0.1"}}'
curl -sS -X POST "$BASE_URL/config" -H 'content-type: application/json' -d '{"id":"demo-device","host":"127.0.0.1","alias":"Demo Device"}'
curl -sS "$BASE_URL/entities"
curl -sS -X POST "$BASE_URL/command" -H 'content-type: application/json' -d '{"contract_version":"automation.runtime.command.v1","command":"refresh","target":{"config_id":"demo-device","device_id":"demo-device"},"params":{},"capability":"device.refresh","capability_requirements":["device.refresh"]}'
`;
}

export function renderContractDoc(options: TemplateScaffoldOptions): string {
  return `# Runtime Contract

Generated by \`piphi-network-create\`.

- Integration ID: \`${options.slug}\`
- Kind: \`${options.kind}\`
- Preset: \`${options.preset}\`
- Domain: \`${options.domain}\`
- Port: \`${options.port}\`

## Required Endpoints

- \`GET /health\`
- \`GET /entities\`
- \`POST /command\`
- \`POST /config\`
- \`GET /ui-config\`

## Automation Command Payload

\`POST /command\` accepts the Core automation runtime contract:

\`\`\`json
{
  "contract_version": "automation.runtime.command.v1",
  "command": "refresh",
  "target": {
    "config_id": "demo-device",
    "device_id": "demo-device",
    "entity_id": null
  },
  "params": {},
  "capability": "device.refresh",
  "capability_requirements": ["device.refresh"]
}
\`\`\`

Return \`{"ok": true, ...}\` for accepted commands. For validation failures, return \`{"ok": false, "error": "unsupported_capability", "message": "..."}\` with an appropriate 4xx status.

## Recommended Endpoints

- \`GET /diagnostics\`
- \`POST /discover\`
- \`POST /config/sync\`
- \`POST /deconfigure\`
- \`GET /state\`
- \`GET /contract\`
- \`GET /events\`
- \`POST /telemetry/example\`

Keep \`manifest.json\`, the contract source file, and route handlers in sync.
`;
}

export function renderProjectReadme(options: TemplateScaffoldOptions, commands: string[]): string {
  return `# ${options.title}

Generated PiPhi ${options.kind} runtime.

## Run locally

\`\`\`bash
${commands.join("\n")}
\`\`\`

The runtime listens on port \`${options.port}\` by default and exposes the common PiPhi runtime route contract:

- \`GET /health\`
- \`GET /diagnostics\`
- \`POST /discover\`
- \`POST /config\`
- \`POST /config/sync\`
- \`POST /deconfigure\`
- \`POST /deconfigure/{config_id}\`
- \`GET /state\`
- \`GET /contract\`
- \`GET /entities\`
- \`GET /events\`
- \`POST /events/device/{config_id}/example\`
- \`POST /telemetry/example\`
- \`POST /telemetry/device/{config_id}/example\`
- \`POST /command\`

## Manifest

\`manifest.json\` is a starter manifest. Before publishing, update:

- \`image\`
- \`version\`
- capabilities and commands
- config fields and identity fields
- entity metadata

## Docker

\`\`\`bash
docker build -t ${options.image} .
docker run --rm -p ${options.port}:${options.port} ${options.image}
\`\`\`
`;
}

export function renderNodeGithubActions(options: TemplateScaffoldOptions, commands: TemplateCommandSet): string {
  return `name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix.node-version }}
      - run: ${commands.installCommand}
      - run: ${commands.checkCommand}
      - run: ${commands.testCommand}
      - run: ${commands.validateCommand}
      - run: docker build -t piphi-runtime-smoke .
`;
}

export function renderPythonGithubActions(options: TemplateScaffoldOptions): string {
  const installTool = options.pythonManager === "pdm"
    ? "python -m pip install pdm"
    : options.pythonManager === "uv"
      ? "python -m pip install uv"
      : "python -m pip install -e .[dev]";
  const installProject = options.pythonManager === "pdm"
    ? "pdm install -G dev"
    : options.pythonManager === "uv"
      ? "uv pip install --system -e .[dev]"
      : "pytest";
  const testCommand = options.pythonManager === "pdm"
    ? "pdm run pytest"
    : options.pythonManager === "uv"
      ? "uv run pytest"
      : "python scripts/validate.py";
  const validateCommand = options.pythonManager === "pdm"
    ? "pdm run python scripts/validate.py"
    : options.pythonManager === "uv"
      ? "uv run python scripts/validate.py"
      : "docker build -t piphi-runtime-smoke .";

  return `name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: \${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: ${installTool}
      - run: ${installProject}
      - run: ${testCommand}
      - run: ${validateCommand}
${options.pythonManager === "pip" ? "" : "      - run: docker build -t piphi-runtime-smoke .\n"}`;
}

export function renderGoGithubActions(): string {
  return `name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24", "1.25"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: \${{ matrix.go-version }}
      - run: go mod tidy
      - run: go test ./...
      - run: go run ./cmd/validate
      - run: docker build -t piphi-runtime-smoke .
`;
}

export function renderReleaseGithubActions(options: TemplateScaffoldOptions, commands: TemplateCommandSet): string {
  const imageRepo = imageRepository(options.image);
  const registryKind = releaseRegistryKind(imageRepo);
  const defaultBranchGroup = "${{ github.event.repository.default_branch }}";
  return `name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Semantic version action
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
          - release
          - custom
      preid:
        description: Prerelease channel for pre* and prerelease actions
        required: true
        default: alpha
        type: choice
        options:
          - alpha
          - beta
          - rc
      custom_version:
        description: Explicit semantic version when release_type is custom
        required: false
        type: string
      push_latest:
        description: Also publish latest for stable releases
        required: true
        default: true
        type: boolean

permissions:
  contents: write
  packages: write

concurrency:
  group: ${options.slug}-release-\${{ github.event.repository.full_name }}
  cancel-in-progress: false

env:
  RELEASE_IMAGE: ${imageRepo}
  RELEASE_REGISTRY_KIND: ${registryKind}
  DOCKERHUB_USERNAME: \${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_USERNAME || secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: \${{ secrets.DOCKERHUB_TOKEN != '' && secrets.DOCKERHUB_TOKEN || secrets.DOCKER_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: \${{ github.ref_name }}

      - name: Require default branch
        shell: bash
        run: |
          set -euo pipefail
          if [[ "\${GITHUB_REF_NAME}" != "${defaultBranchGroup}" ]]; then
            echo "Releases must be triggered from ${defaultBranchGroup}." >&2
            exit 1
          fi
${renderReleaseSetup(options)}
      - name: Install project
        run: ${commands.installCommand}

      - name: Run checks
        run: ${commands.checkCommand}

      - name: Run tests
        run: ${commands.testCommand}

      - name: Validate scaffold contract
        run: ${commands.validateCommand}

      - name: Validate release script
        run: |
          python3 -m py_compile scripts/release.py
          python3 scripts/release.py --bump patch --docker-image "\${RELEASE_IMAGE}" --dry-run

      - name: Resolve release version
        id: version
        shell: bash
        run: |
          set -euo pipefail
          if [[ "\${{ inputs.release_type }}" == "custom" ]]; then
            if [[ -z "\${{ inputs.custom_version }}" ]]; then
              echo "custom_version is required when release_type=custom" >&2
              exit 1
            fi
            VERSION=$(python scripts/release.py --set-version "\${{ inputs.custom_version }}" --docker-image "\${RELEASE_IMAGE}")
          else
            VERSION=$(python scripts/release.py --bump "\${{ inputs.release_type }}" --preid "\${{ inputs.preid }}" --docker-image "\${RELEASE_IMAGE}")
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          if [[ "$VERSION" == *-* ]]; then
            echo "stable=false" >> "$GITHUB_OUTPUT"
          else
            echo "stable=true" >> "$GITHUB_OUTPUT"
          fi
          echo "Resolved version: $VERSION"

      - name: Reject latest on prereleases
        shell: bash
        run: |
          set -euo pipefail
          if [[ "\${{ inputs.push_latest }}" == "true" && "\${{ steps.version.outputs.stable }}" != "true" ]]; then
            echo "latest can only be published for stable releases." >&2
            exit 1
          fi

      - name: Fail if release tag already exists
        shell: bash
        run: |
          set -euo pipefail
          TAG="v\${{ steps.version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists locally." >&2
            exit 1
          fi
          if git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists on origin." >&2
            exit 1
          fi

      - name: Commit release metadata locally
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          for file in pyproject.toml package.json go.mod; do
            if [[ -f "$file" ]]; then
              git add "$file"
            fi
          done
          git commit -m "release: v\${{ steps.version.outputs.version }}"
          git tag "v\${{ steps.version.outputs.version }}"

      - name: Capture release revision
        id: git
        shell: bash
        run: |
          set -euo pipefail
          echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Require supported registry
        if: \${{ env.RELEASE_REGISTRY_KIND == 'unsupported' }}
        shell: bash
        run: |
          echo "Use ghcr.io/org/image, docker.io/org/image, or org/image for RELEASE_IMAGE." >&2
          exit 1

      - name: Log in to GitHub Container Registry
        if: \${{ env.RELEASE_REGISTRY_KIND == 'ghcr' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: \${{ env.RELEASE_REGISTRY_KIND == 'dockerhub' && env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: \${{ env.DOCKERHUB_USERNAME }}
          password: \${{ env.DOCKERHUB_TOKEN }}

      - name: Require Docker Hub credentials
        if: \${{ env.RELEASE_REGISTRY_KIND == 'dockerhub' && (env.DOCKERHUB_USERNAME == '' || env.DOCKERHUB_TOKEN == '') }}
        shell: bash
        run: |
          echo "Set DOCKERHUB_USERNAME/DOCKERHUB_TOKEN or DOCKER_USERNAME/DOCKER_PASSWORD secrets before releasing." >&2
          exit 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: \${{ env.RELEASE_IMAGE }}
          tags: |
            type=raw,value=\${{ steps.version.outputs.version }}
            type=raw,value=latest,enable=\${{ inputs.push_latest && steps.version.outputs.stable == 'true' }}
          labels: |
            org.opencontainers.image.title=${options.title}
            org.opencontainers.image.description=PiPhi ${options.kind} runtime generated by piphi-network-create.
            org.opencontainers.image.source=\${{ github.server_url }}/\${{ github.repository }}
            org.opencontainers.image.url=\${{ github.server_url }}/\${{ github.repository }}
            org.opencontainers.image.revision=\${{ steps.git.outputs.sha }}
            org.opencontainers.image.version=\${{ steps.version.outputs.version }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: \${{ steps.meta.outputs.tags }}
          labels: \${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Push release commit and tag
        shell: bash
        run: |
          set -euo pipefail
          git push origin HEAD:\${GITHUB_REF_NAME}
          git push origin "v\${{ steps.version.outputs.version }}"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v\${{ steps.version.outputs.version }}
          generate_release_notes: true
          prerelease: \${{ steps.version.outputs.stable != 'true' }}
          name: v\${{ steps.version.outputs.version }}

      - name: Release summary
        shell: bash
        run: |
          echo "Published \${{ env.RELEASE_IMAGE }}:\${{ steps.version.outputs.version }}" >> "$GITHUB_STEP_SUMMARY"
          if [[ "\${{ inputs.push_latest }}" == "true" && "\${{ steps.version.outputs.stable }}" == "true" ]]; then
            echo "Published \${{ env.RELEASE_IMAGE }}:latest" >> "$GITHUB_STEP_SUMMARY"
          fi
          echo "Release revision: \${{ steps.git.outputs.sha }}" >> "$GITHUB_STEP_SUMMARY"
`;
}

export function renderReleaseGuide(options: TemplateScaffoldOptions): string {
  return `# Release

This project includes a release workflow generated by \`piphi-network-create\`.

Before cutting a release:

- Set \`manifest.json.version\` to the release version.
- Set \`runtime.linux.container.image\` to the final registry image.
- Set \`maintainer.name\` and \`maintainer.website\` to the publishing owner.
- Run the local validation and conformance tests.
- Run \`piphi-network-create publish-check -C .\` from this project.

The generated workflow is triggered manually from GitHub Actions. It bumps the
semantic version, updates release metadata, commits and tags the release, builds
a multi-architecture Docker image, pushes it, and creates a GitHub release.

Images starting with \`ghcr.io/\` publish to GitHub Container Registry. Images
using \`docker.io/org/image:tag\` or \`org/image:tag\` publish to Docker Hub with
the \`DOCKERHUB_USERNAME\` and \`DOCKERHUB_TOKEN\` repository secrets.

Current image target:

\`\`\`text
${options.image}
\`\`\`
`;
}

function imageRepository(image: string): string {
  const clean = image.split("@", 1)[0]?.trim() ?? "";
  const lastSlash = clean.lastIndexOf("/");
  const lastColon = clean.lastIndexOf(":");
  return lastColon > lastSlash ? clean.slice(0, lastColon) : clean;
}

function releaseRegistryKind(imageRepo: string): "dockerhub" | "ghcr" | "unsupported" {
  if (imageRepo.startsWith("ghcr.io/")) {
    return "ghcr";
  }
  const firstSegment = imageRepo.split("/", 1)[0] ?? "";
  if (imageRepo.startsWith("docker.io/") || (imageRepo.includes("/") && !firstSegment.includes(".") && !firstSegment.includes(":"))) {
    return "dockerhub";
  }
  return "unsupported";
}

export function renderReleaseScript(): string {
  return `#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Self

SEMVER_RE = re.compile(
    r"^(0|[1-9]\\d*)\\."
    r"(0|[1-9]\\d*)\\."
    r"(0|[1-9]\\d*)"
    r"(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?"
    r"(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$"
)
PYPROJECT_VERSION_RE = re.compile(r'(?m)^(version\\s*=\\s*")([^"]+)(")$')
PACKAGE_VERSION_RE = re.compile(r'(?m)^\\s*"version"\\s*:\\s*"([^"]+)"')
DEFAULT_PREID = "alpha"
BUMP_CHOICES = (
    "major",
    "minor",
    "patch",
    "premajor",
    "preminor",
    "prepatch",
    "prerelease",
    "release",
)
PREID_CHOICES = ("alpha", "beta", "rc")


@dataclass(frozen=True, slots=True)
class SemVer:
    major: int
    minor: int
    patch: int
    prerelease: tuple[str, ...] = ()
    build: tuple[str, ...] = ()

    @classmethod
    def parse(cls, value: str) -> Self:
        match = SEMVER_RE.match(str(value).strip())
        if match is None:
            raise ValueError(f"Invalid semantic version: {value}")
        prerelease = tuple(match.group(4).split(".")) if match.group(4) else ()
        build = tuple(match.group(5).split(".")) if match.group(5) else ()
        return cls(int(match.group(1)), int(match.group(2)), int(match.group(3)), prerelease, build)

    def __str__(self) -> str:
        value = f"{self.major}.{self.minor}.{self.patch}"
        if self.prerelease:
            value = f"{value}-" + ".".join(self.prerelease)
        if self.build:
            value = f"{value}+" + ".".join(self.build)
        return value

    def without_prerelease(self) -> Self:
        return SemVer(self.major, self.minor, self.patch, (), self.build)

    def with_prerelease(self, *parts: str) -> Self:
        return SemVer(self.major, self.minor, self.patch, tuple(parts), self.build)

    def stable_key(self) -> tuple[int, int, int]:
        return self.major, self.minor, self.patch

    def compare(self, other: Self) -> int:
        if self.stable_key() != other.stable_key():
            return -1 if self.stable_key() < other.stable_key() else 1
        if not self.prerelease and not other.prerelease:
            return 0
        if not self.prerelease:
            return 1
        if not other.prerelease:
            return -1
        return _compare_identifiers(self.prerelease, other.prerelease)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Bump PiPhi runtime release metadata.")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--bump", choices=BUMP_CHOICES, help="Increment the current version.")
    mode.add_argument("--set-version", help="Set an explicit semantic version.")
    parser.add_argument("--preid", choices=PREID_CHOICES, default=DEFAULT_PREID)
    parser.add_argument("--repo-root", default=None)
    parser.add_argument("--manifest", default="manifest.json")
    parser.add_argument("--pyproject", default="pyproject.toml")
    parser.add_argument("--package-json", default="package.json")
    parser.add_argument("--docker-image", default=None)
    parser.add_argument("--no-pin-container-image", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def resolve_repo_root(value: str | None) -> Path:
    return Path(value).expanduser().resolve() if value else Path(__file__).resolve().parents[1]


def resolve_path(repo_root: Path, value: str) -> Path:
    path = Path(value).expanduser()
    return (path if path.is_absolute() else repo_root / path).resolve()


def read_version_file(path: Path) -> tuple[str, SemVer] | None:
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    if path.name == "pyproject.toml":
        match = PYPROJECT_VERSION_RE.search(text)
        if match is None:
            raise ValueError("Unable to find project version in pyproject.toml")
        return text, SemVer.parse(match.group(2))
    if path.name == "package.json":
        payload = json.loads(text)
        return text, SemVer.parse(str(payload.get("version") or ""))
    return None


def write_version_file(path: Path, text: str, version: str) -> None:
    if path.name == "pyproject.toml":
        updated, count = PYPROJECT_VERSION_RE.subn(rf'\\g<1>{version}\\g<3>', text, count=1)
        if count != 1:
            raise ValueError("Unable to update project version in pyproject.toml")
        path.write_text(updated, encoding="utf-8")
        return
    if path.name == "package.json":
        payload = json.loads(text)
        payload["version"] = version
        path.write_text(json.dumps(payload, indent=2) + "\\n", encoding="utf-8")


def resolve_target_version(current: SemVer, *, bump: str | None, set_version: str | None, preid: str) -> SemVer:
    if set_version is not None:
        target = SemVer.parse(set_version.strip())
        if target.compare(current) <= 0:
            raise ValueError(f"Explicit version must be newer than the current version ({current})")
        return target
    if bump is None:
        raise ValueError("Either --bump or --set-version is required")
    return bump_version(current, bump=bump, preid=preid)


def bump_version(current: SemVer, *, bump: str, preid: str) -> SemVer:
    stable = current.without_prerelease()
    if bump == "major":
        return SemVer(stable.major + 1, 0, 0)
    if bump == "minor":
        return SemVer(stable.major, stable.minor + 1, 0)
    if bump == "patch":
        return SemVer(stable.major, stable.minor, stable.patch + 1)
    if bump == "premajor":
        return SemVer(stable.major + 1, 0, 0).with_prerelease(preid, "1")
    if bump == "preminor":
        return SemVer(stable.major, stable.minor + 1, 0).with_prerelease(preid, "1")
    if bump == "prepatch":
        return SemVer(stable.major, stable.minor, stable.patch + 1).with_prerelease(preid, "1")
    if bump == "prerelease":
        return bump_prerelease(current, preid=preid)
    if bump == "release":
        if not current.prerelease:
            raise ValueError("Cannot promote a stable version. Use patch/minor/major or --set-version instead.")
        return current.without_prerelease()
    raise ValueError(f"Unsupported bump type: {bump}")


def bump_prerelease(current: SemVer, *, preid: str) -> SemVer:
    if not current.prerelease:
        return SemVer(current.major, current.minor, current.patch + 1).with_prerelease(preid, "1")
    stable = current.without_prerelease()
    if current.prerelease[0] != preid:
        return stable.with_prerelease(preid, "1")
    suffix = list(current.prerelease[1:])
    if not suffix:
        return stable.with_prerelease(preid, "1")
    if suffix[-1].isdigit():
        suffix[-1] = str(int(suffix[-1]) + 1)
    else:
        suffix.append("1")
    return stable.with_prerelease(preid, *suffix)


def _compare_identifiers(left: tuple[str, ...], right: tuple[str, ...]) -> int:
    for left_part, right_part in zip(left, right):
        if left_part == right_part:
            continue
        left_numeric = left_part.isdigit()
        right_numeric = right_part.isdigit()
        if left_numeric and right_numeric:
            return -1 if int(left_part) < int(right_part) else 1
        if left_numeric != right_numeric:
            return -1 if left_numeric else 1
        return -1 if left_part < right_part else 1
    if len(left) == len(right):
        return 0
    return -1 if len(left) < len(right) else 1


def image_repository(image: str) -> str:
    image = image.strip()
    if "@" in image:
        image = image.split("@", 1)[0]
    last_slash = image.rfind("/")
    last_colon = image.rfind(":")
    if last_colon > last_slash:
        return image[:last_colon]
    return image


def infer_primary_container_repo(manifest: dict) -> str | None:
    top_level_image = manifest.get("image")
    if isinstance(top_level_image, str) and top_level_image.strip():
        return image_repository(top_level_image)
    repos: set[str] = set()
    runtime = manifest.get("runtime")
    if isinstance(runtime, dict):
        for platform_config in runtime.values():
            if not isinstance(platform_config, dict):
                continue
            container = platform_config.get("container")
            if not isinstance(container, dict):
                continue
            image = container.get("image")
            if isinstance(image, str) and image.strip():
                repos.add(image_repository(image))
    if not repos:
        return None
    if len(repos) > 1:
        raise ValueError("Multiple runtime container image repositories found; pass --docker-image explicitly.")
    return next(iter(repos))


def update_primary_container_images(manifest: dict, *, docker_image: str, version: str) -> None:
    tagged_image = f"{docker_image}:{version}"
    if isinstance(manifest.get("image"), str) and image_repository(manifest["image"]) == docker_image:
        manifest["image"] = tagged_image
    runtime = manifest.get("runtime")
    if not isinstance(runtime, dict):
        return
    for platform_config in runtime.values():
        if not isinstance(platform_config, dict):
            continue
        container = platform_config.get("container")
        if not isinstance(container, dict):
            continue
        image = container.get("image")
        if isinstance(image, str) and image.strip() and image_repository(image) == docker_image:
            container["image"] = tagged_image


def main() -> int:
    args = parse_args()
    repo_root = resolve_repo_root(args.repo_root)
    manifest_path = resolve_path(repo_root, args.manifest)
    pyproject_path = resolve_path(repo_root, args.pyproject)
    package_path = resolve_path(repo_root, args.package_json)

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest_version = SemVer.parse(str(manifest.get("version") or "").strip())
    version_files = [
        (path, result)
        for path, result in [
            (pyproject_path, read_version_file(pyproject_path)),
            (package_path, read_version_file(package_path)),
        ]
        if result is not None
    ]
    for path, (_text, version) in version_files:
        if version.compare(manifest_version) != 0:
            raise ValueError(f"Version mismatch: {path.name}={version} manifest.json={manifest_version}")

    target = resolve_target_version(manifest_version, bump=args.bump, set_version=args.set_version, preid=args.preid)
    target_version = str(target)

    if args.dry_run:
        print(target_version)
        return 0

    manifest["version"] = target_version
    if not args.no_pin_container_image:
        docker_image = args.docker_image or infer_primary_container_repo(manifest)
        if docker_image:
            update_primary_container_images(manifest, docker_image=docker_image, version=target_version)

    manifest_path.write_text(json.dumps(manifest, indent=2) + "\\n", encoding="utf-8")
    for path, (text, _version) in version_files:
        write_version_file(path, text, target_version)
    print(target_version)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"release.py failed: {exc}", file=sys.stderr)
        raise SystemExit(1)
`;
}

function renderReleaseSetup(options: TemplateScaffoldOptions): string {
  if (options.language === "node") {
    return `      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
`;
  }
  if (options.language === "python") {
    return `      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: python -m pip install --upgrade pip
`;
  }
  return `      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
`;
}
